INSERT INTO TB_PARTICIPANT (NAME, EMAIL) VALUES ('José Silva', 'jose@gmail.com')
INSERT INTO TB_PARTICIPANT (NAME, EMAIL) VALUES ('Tiago Faria', 'tiago@gmail.com')
INSERT INTO TB_PARTICIPANT (NAME, EMAIL) VALUES ('Maria do Rosário', 'maria@gmail.com')
INSERT INTO TB_PARTICIPANT (NAME, EMAIL) VALUES ('Teresa Silva', 'teresa@gmail.com')

INSERT INTO TB_CATEGORY (DESCRIPTION) VALUES ('CURSO')
INSERT INTO TB_CATEGORY (DESCRIPTION) VALUES ('OFICINA')

INSERT INTO TB_ACTIVITY (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('Curso de HTML', 'Aprenda HTML de forma prática', 80.00, 1)
INSERT INTO TB_ACTIVITY (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('Oficina de GitHub', 'Controle versões de seus projetos', 50.00, 2)

INSERT INTO TB_BLOCK (BEGIN_TIME, END_TIME, ACTIVITY_ID) VALUES (TIMESTAMP WITH TIME ZONE '2017-09-25T08:00:00Z', TIMESTAMP WITH TIME ZONE '2017-09-25T11:00:00Z', 1)
INSERT INTO TB_BLOCK (BEGIN_TIME, END_TIME, ACTIVITY_ID) VALUES (TIMESTAMP WITH TIME ZONE '2017-09-25T14:00:00Z', TIMESTAMP WITH TIME ZONE '2017-09-25T18:00:00Z', 2)
INSERT INTO TB_BLOCK (BEGIN_TIME, END_TIME, ACTIVITY_ID) VALUES (TIMESTAMP WITH TIME ZONE '2017-09-25T08:00:00Z', TIMESTAMP WITH TIME ZONE '2017-09-25T11:00:00Z', 2)

INSERT INTO TB_ACTIVITY_PARTICIPANT (ACTIVITY_ID, PARTICIPANT_ID) VALUES (1, 1)
INSERT INTO TB_ACTIVITY_PARTICIPANT (ACTIVITY_ID, PARTICIPANT_ID) VALUES (2, 1)
INSERT INTO TB_ACTIVITY_PARTICIPANT (ACTIVITY_ID, PARTICIPANT_ID) VALUES (1, 2)
INSERT INTO TB_ACTIVITY_PARTICIPANT (ACTIVITY_ID, PARTICIPANT_ID) VALUES (1, 3)
INSERT INTO TB_ACTIVITY_PARTICIPANT (ACTIVITY_ID, PARTICIPANT_ID) VALUES (2, 3)
INSERT INTO TB_ACTIVITY_PARTICIPANT (ACTIVITY_ID, PARTICIPANT_ID) VALUES (2, 4)